export const images = {
  back1: require('../../assets/images/back1.png'),
  back2: require('../../assets/images/back2.png'),
  back3: require('../../assets/images/back3.png'),
  back4: require('../../assets/images/back4.png'),
  back5: require('../../assets/images/back5.png'),
  back6: require('../../assets/images/back6.png'),
  back7: require('../../assets/images/back7.png'),
  box: require('../../assets/images/box.png'),

  calendar: require('../../assets/images/calendar.png'),
  camera: require('../../assets/images/camera.png'),
  call: require('../../assets/images/call.png'),
  chart: require('../../assets/images/chart.png'),
  clock1: require('../../assets/images/clock1.png'),
  clock2: require('../../assets/images/clock2.png'),
  clock3: require('../../assets/images/clock3.png'),
  clock4: require('../../assets/images/clock4.png'),
  close: require('../../assets/images/close.png'),

  edit: require('../../assets/images/edit.png'),
  edit_remove: require('../../assets/images/edit_remove.png'),
  envelope: require('../../assets/images/envelope.png'),
  facebook: require('../../assets/images/facebook.png'),
  femenine: require('../../assets/images/femenine.png'),
  follow: require('../../assets/images/follow.png'),
  girl: require('../../assets/images/girl.png'),
  gear: require('../../assets/images/gear.png'),
  goback: require('../../assets/images/goback.png'),
  gold: require('../../assets/images/gold.png'),
  google: require('../../assets/images/google.png'),
  home: require('../../assets/images/home.png'),
  india: require('../../assets/images/india.png'),

  interest_animals: require('../../assets/images/animals.png'),
  interest_arts: require('../../assets/images/arts.png'),
  interest_automobile: require('../../assets/images/automobile.png'),
  interest_food: require('../../assets/images/food.png'),
  interest_fashion: require('../../assets/images/fashion.png'),
  interest_nature: require('../../assets/images/nature.png'),
  interest_technology: require('../../assets/images/technology.png'),
  interest_traveling: require('../../assets/images/traveling.png'),

  locatePlace: require('../../assets/images/locate-place.png'),
  logo: require('../../assets/images/logo.png'),
  logout: require('../../assets/images/logout.png'),
  lock: require('../../assets/images/lock.png'),
  man: require('../../assets/images/man.png'),
  manUser: require('../../assets/images/man-user.png'),
  mars: require('../../assets/images/mars.png'),
  menu: require('../../assets/images/menu.png'),
  russia: require('../../assets/images/russia.png'),
  score: require('../../assets/images/score.png'),
  search: require('../../assets/images/search.png'),
  spain: require('../../assets/images/spain.png'),
  timeline: require('../../assets/images/timeline.png'),
  trophy1: require('../../assets/images/trophy1.png'),
  trophy2: require('../../assets/images/trophy2.png'),
  trophy3: require('../../assets/images/trophy3.png'),
  twitter: require('../../assets/images/twitter.png'),
  us: require('../../assets/images/united-states.png'),
  world: require('../../assets/images/world.png'),

  nav : require('../../assets/images/nav.png'),
  happy_eyes : require('../../assets/images/happy_eyes.png'),
  plus : require('../../assets/images/plus.png'),
  send : require('../../assets/images/send.png'),
  heart: require('../../assets/images/heart.png'),
  home_outline: require('../../assets/images/home-outline.png'),
  heart_white: require('../../assets/images/heart-white.png'),
  msg: require('../../assets/images/msg.png'),
  shop : require('../../assets/images/shopping.png'),
  friend: require('../../assets/images/friends.png'),
  leave : require('../../assets/images/leave.png'),
  white_plus: require('../../assets/images/white_plus.png'),
  optBack: require('../../assets/images/optBack.png'),
  yellow_circle: require('../../assets/images/yellow_circle.png'),
  watch : require('../../assets/images/watch.png'),

  ball_gif : require('../../assets/gif/waveball1.gif'),
  rect_gif : require('../../assets/gif/waverect.gif'),
};
