const screens = {
  SelectLanguage: 'SelectLanguage',
  SelectCountry: 'SelectCountry',
  RequestOtp: 'RequestOtp',
  VerifyOtp: 'VerifyOtp',
  Home: 'Home',
  Login: 'Login',
  Register: 'Register',
  ViewProfile: 'ViewProfile',
  MyProfile: 'MyProfile',
  EditProfile: 'EditProfile',
  Chat: 'Chat',
  GroupInfo: 'GroupInfo',
  Group: 'Group',
  Scoreboard: 'Scoreboard',
  Timer: 'Timer',
  Bazaar: 'Bazaar',
  Conversation: 'Conversation',
  Feeds: 'Feeds',
  Notifications: 'Notifications',
  Search: 'Search',
  TimeCount: 'TimeCount',
};

export default screens;
